// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEGtk_Qo7Cm9beeHQJm46lbxaXW_odtb0',
    appId: '1:904073852438:web:f95c5e32a5fb7a6cd96737',
    messagingSenderId: '904073852438',
    projectId: 'cafem-96c62',
    authDomain: 'cafem-96c62.firebaseapp.com',
    storageBucket: 'cafem-96c62.appspot.com',
    measurementId: 'G-WQFGJNV38N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBooC3TRDpJfWd4WJRTjcwqrw0wVOzse4A',
    appId: '1:904073852438:android:f54617c3c0801dc0d96737',
    messagingSenderId: '904073852438',
    projectId: 'cafem-96c62',
    storageBucket: 'cafem-96c62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEx8VVmMlkprfpoT4ROBUQSyaxNB-GCXA',
    appId: '1:904073852438:ios:fa69a2bec5aa16e3d96737',
    messagingSenderId: '904073852438',
    projectId: 'cafem-96c62',
    storageBucket: 'cafem-96c62.appspot.com',
    iosBundleId: 'com.example.cafem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEx8VVmMlkprfpoT4ROBUQSyaxNB-GCXA',
    appId: '1:904073852438:ios:fa69a2bec5aa16e3d96737',
    messagingSenderId: '904073852438',
    projectId: 'cafem-96c62',
    storageBucket: 'cafem-96c62.appspot.com',
    iosBundleId: 'com.example.cafem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEGtk_Qo7Cm9beeHQJm46lbxaXW_odtb0',
    appId: '1:904073852438:web:dc452e026a9910e2d96737',
    messagingSenderId: '904073852438',
    projectId: 'cafem-96c62',
    authDomain: 'cafem-96c62.firebaseapp.com',
    storageBucket: 'cafem-96c62.appspot.com',
    measurementId: 'G-18LR5ZV7NG',
  );
}
